#+TITLE: My Linux Journey
#+STARTUP: indent

*The World's Best OS.*

* Gentoo
** ebuild
http://devmanual.gentoo.org/function-reference/install-functions/index.html

** kernel
- 用 make localmodconfig 去掉一些沒用到的
- 把 lspci -n (sys-apps/pciutils) 貼到 http://kmuto.jp/debian/hcl/，觀察需要的驅動名，然後在 make menuconfig 裏用 h 搜索

** Print
*** hplip
see: http://en.gentoo-wiki.com/wiki/CUPS#HP_Printers

** Eix
查看package 属于哪个 overlay
#+begin_src sh
eix -Jc
#+end_src

** Tips
http://gentoovps.net/gentoo-portage-tips/

** Time
*** hwclock
usage:
#+begin_example
hwclock -w :write current time to hardware time
hwclock -s :set current time from hardware time
#+end_example
*** ntpd
#+begin_src sh
emerge net-misc/openntpd
#+end_src
usage:
#+begin_example
ntpd -s :sync time
/etc/init.d/ntpd (start|stop|restart)
#+end_example

* ArchLinux
This section details archlinux in my eeepc x101 notebook.
DEADLINE: <2013-03-03 Sun>

** Disk Infomation
#+begin_src sh
parted /dev/sda u s p
#+end_src
#+begin_example
Model: ATA JMicron (scsi)
Disk /dev/sda: 15740928s
Sector size (logical/physical): 512B/512B
Partition Table: gpt
Disk Flags:

Number  Start    End        Size       File system  Name       Flags
 1      2048s    4095s      2048s                   BIOS_GRUB  bios_grub
 2      4096s    208895s    204800s    ext2         ARCH_BOOT  boot
 3      208896s  15732735s  15523840s  ext4         ARCH_ROOT
#+end_example
#+begin_src sh
sed -e '/^#.*$/d' -e '/^ *$/d' /etc/fstab
#+end_src
#+begin_example
/dev/sda3               /               btrfs           rw,relatime,ssd,space_cache     0 1
/dev/sda2               /boot           ext2            rw,relatime     0 2
#+end_example

** System Time
Time zone setting.
#+begin_src sh
ln -s /usr/share/zoneinfo/Europe/Athens /etc/localtime
#+end_src
Use UTC in hardware clock.
#+begin_src sh
hwclock --systohc --utc
#+end_src
** Locale
#+begin_src sh
sed '/^#.*$/d' /etc/locale.gen
#+end_src
#+begin_example
en_US.UTF-8 UTF-8
en_US ISO-8859-1
zh_CN.GB18030 GB18030
zh_CN.GBK GBK
zh_CN.UTF-8 UTF-8
zh_CN GB2312
#+end_example
#+begin_src sh
cat /etc/locale.conf
#+end_src
#+begin_example
LANG="en_US.UTF-8"
LC_CTYPE="zh_CN.UTF-8"
#+end_example

** Install a New System
netcfg has been installed default.
#+begin_src sh
pacstrap /mnt base base-devel \
              # net-tools wireless_tools \
              # dialog elinks \
              w3m wpa_supplicant \
              htop git zsh grml-zsh-config
#+end_src

Add this to {{{/etc/pacman.conf}}}, then
#+begin_example
[archlinuxfr]
Server = http://repo.archlinux.fr/$arch
#+end_example
install yaourt, and delete upon text.
#+begin_src sh
pacman -Syy yaourt
#+end_src

** Users
Rule to create a new user.
#+begin_src sh
useradd -m -g users -G wheel,storage,power -s /bin/zsh <username>
#+end_src

** Graphic (base system)
#+begin_src sh
pacman -S alsa-utils \
          xorg-server{,-utils} xorg-{xinit,utils} \
          xf86-video-{vesa,intel} xf86-input-synaptics \
          xorg-twm xterm #for test
#+end_src

Fonts I use.
#+begin_src sh
pacman -S ttf-{dejavu,droid,inconsolata} \ #,envy-code-r} \
          wqy-microhei
          terminus-font
#+end_src

*** enlightenment17
#+begin_src sh
pacman -S enlightenment17
yaourt -S e-modules-extra-svn terminology econnman-svn
#+end_src

#+begin_src sh
pacman -S lxdm
systemctl enable lxdm.service
#+end_src


*** monsterwm
pacman -S dmenu

** Daily Software
#+begin_src sh
pacman -S vim emacs \
          #opera chromium \
          luakit flashplugin \
          fcitx fcitx-{configtool,gtk2,gtk3,qt} \
          mplayer feh
          rxvt-unicode zathura
#+end_src


* Fedora
** Fetch Package Only
see: [[http://www.cyberciti.biz/faq/yum-downloadonly-plugin/][How To Download a RPM Package Using yum Command Without Installing On Linux]]
#+begin_src sh
yum install yum-downloadonly
yum install abc --downloadonly
#+end_src
Packages will in /var/cache/
* Tips
** Http Server
#+begin_src sh
python -m SimpleHTTPServer 8080
#+end_src

** wpa_supplicant

** Zsh
[[https://wiki.archlinux.org/index.php/Zsh#Making_Zsh_your_default_shell][ArchLinux Wiki - Making Zsh default]]
** 解压 .deb
#+begin_src sh
ar -x *.deb
#+end_src

** 解压 .rpm
#+begin_src sh
rpm2targz *.rpm
#+end_src
** torrent 转换 magnet
http://stackoverflow.com/questions/12479570/given-a-torrent-file-how-do-i-generate-a-magnet-link-in-python
** Dvorak
*** Xorg
In File /etc/X11/xorg.conf.d/10-evdev.conf
#+begin_src conf
...

Section "InputClass"
        Identifier "evdev keyboard catchall"
        MatchIsKeyboard "on"
        MatchDevicePath "/dev/input/event*"
        Driver "evdev"

        # setting keyboard layout for slim
        # TODO: Do not use this in future
        Option "XkbLayout" "us"
        Option "XkbVariant" "dvorak"
        Option "XkbOptions" "terminate:ctrl_alt_bksp"
EndSection

...
#+end_src

*** Xmodmap
* Emacs
- Delete a whole line
#+begin_example
M-x kill-whole-line <C-S-backspace>
#+end_example

- Backward kill
#+begin_example
C-u 0 C-k
#+end_example

** installer
https://github.com/salborini/emacs-installer
** keyfreq
- http://ergoemacs.org/emacs/command-frequency.html
* Git
** 分治合并
http://gitbook.liuhui998.com/5_3.html

** change remote

http://stackoverflow.com/questions/2432764/how-to-change-a-remote-repository-uri-using-git
https://help.github.com/articles/changing-a-remote-s-url

use this command
#+BEGIN_SRC sh
git remote set-url origin https://github.com/ironyKuU/org.git
#+END_SRC

this project's url:
#+BEGIN_SRC sh
git remote -v
#+END_SRC
#+BEGIN_EXAMPLE
origin	https://github.com/ironyKuU/org.git (fetch)
origin	https://github.com/ironyKuU/org.git (push)
#+END_EXAMPLE

* SSH
** ~/.ssh/config
http://nerderati.com/2011/03/simplify-your-life-with-an-ssh-config-file/
http://www.lainme.com/doku.php/blog/2011/01/%E4%BD%BF%E7%94%A8ssh_config

* Wine

** 不自动关联、生成菜单
http://forum.ubuntu.org.cn/viewtopic.php?f=171&t=377702&start=15
http://forum.ubuntu.org.cn/viewtopic.php?t=377637&p=2763361

** 完全卸载
http://jay4rest.wordpress.com/2009/11/28/how-to-completely-remove-w-i-n-e/

