#+TITLE: Number Theory
#+DATE: <2013-11-06>

* GCD (Greatest Common Divisor)

** Euclidean Algorithm

- \(\gcd(a, b) = \gcd(b, a \bmod b)\)
#+begin_src cpp
int gcd(int a,int b) {
    return b ? gcd(b, a%b) : a;
}
#+end_src

- 非递归形式
#+begin_src cpp
typedef long long ll;

ll gcd(ll a,ll b){
    if (a == 0) return 1;
    if (a < 0) return gcd(-a,b);
    while (b) {
        ll t=a%b; a=b; b=t;
    }
    return a;
}


//据说是运行次数最少的
int gcd( int a, int b )
{
   if (a == 0) return 1;
   if (a < 0) return gcd(-a,b);
   int r, e;
   while (b != 0)
   {
      r = a%b;
      e = b-r;
      if (r > e) //需要改成 |r| > |e|
         r = e;

      a = b;
      b = r;
   }
   return a;
}
#+end_src

** Extended GCD

- [[http://zh.wikipedia.org/wiki/%E8%A3%B4%E8%9C%80%E5%AE%9A%E7%90%86][Bézout's identity 裴蜀定理]]\\
  对任意两个整数\(a\)、\(b\)，设\(d\)是它们的最大公约数。
  那么关于未知数\(x\)和\(y\)的线性丢番图方程（称为裴蜀等式）：
  \[ax + by = m\]
  有整数解\((x，y)\)当且仅当\(m\)是\(d\)的倍数。裴蜀等式有解时必然有无穷多个解。
  \(m=1\)时，方程有解当且仅当\(a\)、\(b\)互质。

  方程有解时，解的集合是
  \[
  \left\{\left(\frac{m}{d}\left(x0 + k\frac{b}{d}\right), \frac{m}{d}\left(y0 - k\frac{a}{d}\right)\right) \mid k\in\mathbb{Z} \right\}
  \]
  其中\((x0,y0)\)是方程\(ax + by = d\)的一个解，可由辗转相除法得到。
  所有解中，有且仅有一个解\((x,y)\)满足\(-b \leq x \leq b\)，\(-a \leq y \leq a\)。

#+begin_src cpp
typedef long long ll;

ll ex_gcd(ll a, ll b, ll& x, ll& y)
{
   ll d;
   if (b == 0) {
       x = 1; y = 0;
       return a;
   }
   d  = ex_gcd(b, a%b, y, x);
   y -= a/b * x;
   return d;
}
#+end_src

* Prime Numbers

#+CAPTION: Number of Primes
#+NAME: tab:number-of-primes

   |     x |          \pi(x) |[fn:1]
   |-------+-----------------|
   |   <r> |             <r> |
   |    10 |               4 |
   |  10^2 |              25 |
   |  10^3 |             168 |
   |  10^4 |           1,229 |
   |  10^5 |           9,592 |
   |  10^6 |          78,498 |
   |  10^7 |         664,579 |
   |  10^8 |       5,761,455 |
   |  10^9 |      50,847,534 |
   | 10^10 |     455,052,511 |
   | 10^11 |   4,118,054,813 |
   | 10^12 |  37,607,912,018 |
   | 10^13 | 346,065,536,839 |

** Sieve of Eratosthenes

#+begin_src cpp
#include <ctime>
#include <cmath>
#include <cstdio>
#include <cstring>
#include <iostream>
using namespace std;

// 前 10^7 个数中有 664,579个素数
const int Limit = 10000000;

bool sieve[Limit + 1];
// int primes[Limit / 2 + 1];
int primes[664590];


void Sieve_of_Eratosthenes()
{
    for (int i = 4; i <= Limit; i += 2) sieve[i] = 1;
    for (int i = 3; i * i <= Limit; i += 2)
        if (!sieve[i])
            for (int j = i * i; j <= Limit; j += i)
                sieve[j] = 1;

    primes[0] = 1; primes[1] = 2;
    for(int i = 3; i <= Limit; i += 2)
        if(!sieve[i])
            primes[++ primes[0]] = i;
}


// http://blog.sina.com.cn/s/blog_48f85e1d0100ns71.html
void Sieve_of_Eratosthenes_2(){ //传说中的2倍压缩筛选素数
    int sievelimit = (sqrt(Limit + .0) - 1) / 2; //只需筛到一半
    int maxindex = (Limit - 1) / 2;
    for(int n = 1; n <= sievelimit; ++ n){
        if(sieve[n] == 0){
            int t = 2*n + 1; //每次表示域增加2n+1
            for(int k = 2*n*(n+1); k <= maxindex; k += t) //从2n(n+1)开始
                sieve[k] = 1;
        }
    }
    primes[0] = 1; primes[1] = 2;
    for(int n = 1; n <= maxindex; ++ n){
        if(sieve[n]==0)
            primes[++ primes[0]] = 2*n+1;//p[n]==0表示的是2*n+1是素数
    }
}


// http://en.wikipedia.org/wiki/Sieve_of_Atkin
void Sieve_of_Atkin()
{
    int root = (int)ceil(sqrt(Limit + .0));
    for (int z = 0; z <= Limit; ++ z) sieve[z] = 0;
    for (int x = 1; x <= root; ++ x)
    {
        for (int y = 1; y <= root; ++ y)
        {
            int n = 4*x*x + y*y;
            if (n <= Limit && (n % 12 == 1 || n % 12 == 5)) sieve[n] ^= 1;
            n = 3*x*x + y*y;
            if (n <= Limit && n % 12 == 7) sieve[n] ^= 1;
            n = 3*x*x - y*y;
            if (x > y && n <= Limit && n % 12 == 11) sieve[n] ^= 1;
        }
    }
    for (int r = 5; r <= root; ++ r)
        if (sieve[r])
            for (int i = r*r; i <= Limit; i += r*r)
                sieve[i] = 0;

    primes[0] = primes[1] = 2; primes[2] = 3;
    for (int a = 5; a <= Limit; ++ a)
        if (sieve[a])
            primes[++ primes[0]] = a;
}


void test(char *title, void run())
{
    time_t op, ed;
    op = clock();

    run();

    ed = clock();

    double dif = (ed - op) * 1000.0 / CLOCKS_PER_SEC;
    printf("Testing %s ...\n", title);
    printf("primes: %d, time use: %.3lf ms.\n", primes[0], dif);
}


int main(int argc, char *argv[])
{
    test("Sieve of Eratosthenes",
         Sieve_of_Eratosthenes);

    memset(sieve, 0, sizeof(sieve));
    test("Sieve of Eratosthenes 2",
         Sieve_of_Eratosthenes_2);

    memset(sieve, 0, sizeof(sieve));
    test("Sieve of Atkin",
         Sieve_of_Atkin);
    return 0;
}
#+end_src

** TODO Miller-Rabin大数判素模板 poLLard-rho大数分解模板

- http://blog.ac521.org/?p=533

*** poj 1811

#+BEGIN_SRC cpp
#include <iostream>
#include <vector>
#include <algorithm>
#include <ctime>
using namespace std;

typedef long long LL;

const int S = 20;


LL muti_mod(LL a, LL b, LL c){ //返回(a*b) mod c,a,b,c<2^63
	a %= c;
	b %= c;
	LL ret = 0;
	while(b){
		if(b&1){
			ret += a;
			if(ret>=c)
				ret -= c;
		}
		a <<= 1;
		if(a>=c)
			a -= c;
		b >>= 1;
	}
	return ret;
}

LL pow_mod(LL x, LL n, LL mod){ //返回x^n mod c ,非递归版
	if(n==1)
		return x%mod;
	int bit[64], k = 0;
	while(n){
		bit[k++] = n&1;
		n >>= 1;
	}
	LL ret = 1;
	for(k = k-1; k>=0; k--){
		ret = muti_mod(ret, ret, mod);
		if(bit[k]==1)
			ret = muti_mod(ret, x, mod);
	}
	return ret;
}

bool check(LL a, LL n, LL x, LL t){ //以a为基，n-1=x*2^t，检验n是不是合数
	LL ret = pow_mod(a, x, n), last = ret;
	for(int i = 1; i<=t; i++){
		ret = muti_mod(ret, ret, n);
		if(ret==1&&last!=1&&last!=n-1)
			return 1;
		last = ret;
	}
	if(ret!=1)
		return 1;
	return 0;
}

bool Miller_Rabin(LL n){
	LL x = n-1, t = 0;
	while((x&1)==0)
		x >>= 1, t++;
	bool flag = 1;
	if(t>=1&&(x&1)==1){
		for(int k = 0; k<S; k++){
			LL a = rand()%(n-1)+1;
			if(check(a, n, x, t)){
				flag = 1;
				break;
			}
			flag = 0;
		}
	}
	if(!flag||n==2)
		return 0;
	return 1;
}

LL gcd(LL a, LL b){
	if(a==0)
		return 1;
	if(a<0)
		return gcd(-a, b);
	while(b){
		LL t = a%b;
		a = b;
		b = t;
	}
	return a;
}

LL Pollard_rho(LL x, LL c){
	LL i = 1, x0 = rand()%x, y = x0, k = 2;
	while(1){
		i++;
		x0 = (muti_mod(x0, x0, x)+c)%x;
		LL d = gcd(y-x0, x);
		if(d!=1&&d!=x){
			return d;
		}
		if(y==x0)
			return x;
		if(i==k){
			y = x0;
			k += k;
		}
	}
}

vector<LL> v;

void findFact(LL n)
{
	if (!Miller_Rabin(n)) {
		v.push_back(n);
		return ;
	}
	LL p = n;
	while (p>=n)
		p = Pollard_rho(p, rand()%(n-1)+1);
	findFact(p);
	findFact(n/p);
}

int main()
{
	srand(time(NULL));
	LL n;
	while (cin >> n && n != -1)
	{
		//cerr << n;
		v.clear();
		findFact(n);
		sort(v.begin(),v.end());
		for (int i = 0; i < v.size(); i ++)
			cout << "    " << v[i] << endl;
		cout << endl;
	}
}
#+END_SRC

*** poj 2429 求一合数分解为两数和最小的情况

#+BEGIN_SRC cpp
#include <algorithm>
#include <iostream>
#include <string.h>
#include <stdio.h>
using namespace std;
typedef __int64 L;
typedef unsigned __int64 UL;
const int COUNT = 6;
L allFactor[65], nFactor;
L fMultiModular(const L & a, L b, const L & n){
	L back(0), tmp(a%n);
	while(b>0){
		if(b&0x1){
			if((back = back+tmp)>n)
				back -= n;
		}
		if((tmp <<= 1)>n)
			tmp -= n;
		b >>= 1;
	}
	return back;
}
L modular_exp(const L & a, L b, const L & n){
	L d(1), tmp(a%n);
	while(b>0){
		if(b&0x1)
			d = fMultiModular(d, tmp, n);
		tmp = fMultiModular(tmp, tmp, n);
		b >>= 1;
	}
	return d;
}
L GCD(L a, L b){
	L c;
	while(b){
		c = b;
		b = a%b;
		a = c;
	}
	return a;
}
L pollard_rho(const L & c, const L & num){
	int i(1), k(2);
	L x = rand()%num;
	L y = x, comDiv;
	do{
		i++;
		if((x = fMultiModular(x, x, num)-c)<0)
			x += num;
		if(x==y)
			break;
		comDiv = GCD((y-x+num)%num, num);
		if(comDiv>1&&comDiv<num)
			return comDiv;
		if(i==k){
			y = x;
			k <<= 1;
		}
	}while(1);
	return num;
}
bool fWitNess(const L & a, const L & n, char t, const L & u){
	L x, y;
	x = modular_exp(a, u, n);
	while(t--){
		y = fMultiModular(x, x, n);
		if(y==1&&x!=1&&x!=n-1)
			return true;
		x = y;
	}
	return y!=1;
}
bool miller_rabin(const L & n, int cnt){
	if(n==1)
		return false;
	if(n==2)
		return true;
	L a, u;
	char t(0);
	for(u = n-1; !(u&0x1); u >>= 1)
		t++;
	for(int i = 1; i<=cnt; i++){
		a = rand()%(n-1)+1;
		if(fWitNess(a, n, t, u))
			return false;
	}
	return true;
}
void fFindFactor(const L & num){
	if(miller_rabin(num, COUNT)){
		allFactor[++nFactor] = num;
		return;
	}
	L factor;
	do{
		factor = pollard_rho(rand()%(num-1)+1, num);
	}while(factor>=num);
	fFindFactor(factor);
	fFindFactor(num/factor);
}
UL NumFactor[650];
int Num[65], Len;
void Factorize(const L & N){
	L tmp = N;
	Len = 0;
	memset(Num, 0, sizeof(Num));
	nFactor = 0;
	fFindFactor(tmp);
	sort(allFactor+1, allFactor+nFactor+1);
	NumFactor[0] = allFactor[1];
	Num[0] = 1;
	for(int i = 2; i<=nFactor; i++){
		if(NumFactor[Len]!=allFactor[i])
			NumFactor[++Len] = allFactor[i];
		Num[Len]++;
	}
}
UL key, a, b, mmin, gcd, lcm, res_a, res_b;
UL num1Factor[650];
int num1[65], len1;
void DFS(int cur, UL value){
	UL s = 1;
	if(cur==len1+1){
		a = value;
		b = key/value;
		if(GCD(a, b)==1){
			a *= gcd;
			b *= gcd;
			if(a+b<mmin){
				mmin = a+b;
				res_a = a<b ? a : b;
				res_b = a>b ? a : b;
			}
		}
		return;
	}
	for(int i = 0; i<=num1[cur]; i++){
		if(value*s>=mmin)
			return;
		DFS(cur+1, value*s);
		s *= num1Factor[cur];
	}
}
int main(){
	while(scanf("%I64u%I64u", &gcd, &lcm)!=EOF){
		if(gcd==lcm){
			printf("%I64u %I64u\n", gcd, lcm);
			continue;
		}
		key = lcm/gcd;
		memset(num1Factor, 0, sizeof(num1Factor));
		memset(num1, 0, sizeof(num1));
		len1 = 0;
		Factorize(key);
		memcpy(num1Factor, NumFactor, sizeof(NumFactor));
		memcpy(num1, Num, sizeof(Num));
		len1 = Len;
		mmin = -1;
		DFS(0, 1);
		printf("%I64u %I64u\n", res_a, res_b);
	}
	return 0;
}
#+END_SRC

*** SQUFOF

#+BEGIN_SRC cpp
/*==================================================*\
 * SQUFOF因子分解,10^18以内因子分解的最快算法
 * 用法：
 * 1、所有case之前调用一次init()
 * 2、连续使用analyze(合数N)，每次不需重新初始化
 * 返回：合数N的一个因子
 * 注意：
 * 1、N不能太大，最好<2^54,以防溢出
 * 2、TABLE_SIZE的值不能更改
 * 3、U32不能用int代替
 * 4、不会因为N有小因子而更快，请先试除小因子
 \*==================================================*/
typedef unsigned long long U64;
typedef unsigned int U32;
const U32 MAX_INDEEP = 10000;
const U32 TABLE_SIZE = 131071;
U32 sqrt_table[TABLE_SIZE] = {0};
class squfof{
	U32 try_ana(U64 N){
		U32 sqrt_n = (U32) sqrt((long double) N);
		U32 P1 = sqrt_n, Q2 = 1, Q1 = N-(U64) P1*P1;
		U32 B, P, Q, step = MAX_INDEEP;
		if(Q1==0)
			return P1;
		while(sqrt_table[Q1%TABLE_SIZE]!=Q1){
			B = (sqrt_n+P1)/Q1;
			P = B*Q1-P1;
			Q = Q2+B*(P1-P);
			P1 = P;
			Q2 = Q1;
			Q1 = Q;
		}
		U32 sqrt_Qi = (U32) sqrt((long double) Q1);
		B = (sqrt_n-P1)/sqrt_Qi;
		P1 = B*sqrt_Qi+P;
		Q2 = sqrt_Qi;
		Q1 = (N-(U64) P1*P1)/Q2;
		P = P1;
		P1 = 0;
		while(P!=P1&&step--){
			P1 = P;
			B = (sqrt_n+P1)/Q1;
			P = B*Q1-P1;
			Q = Q2+B*(P1-P);
			Q2 = Q1;
			Q1 = Q;
		}
		return P;
	}
public:
	init(){
		for (U32 i = 0; i < (1 << 16); i++)
		sqrt_table[i * i % TABLE_SIZE] = i * i;
	}
	U32 analyze(U64 N){
		U32 k, t = 0;
		for(k = 1; t==0||t==1; k++){
			t = __gcd(try_ana(k*N), N);
		}
		return t;
	}
};
#+END_SRC

* 因数

+ [[http://uva.onlinejudge.org/index.php?option=com_onlinejudge&Itemid=8&page=show_problem&problem=2716][UVA/11669 - Non-Decreasing Prime Sequence]]
  - Q: 一数范围[a, b]中所有数按素因子序列长度排序（如10为2,2,5），长度相同时按字典序排。问第k小数的素因子序列。
  - A: O(n) 分解 2 ~ 1000000 质因子，排序后转化为区间第k小数问题（划分树）。

* Modular Arithmetic

** Knowledge

*** a%b%c is not always equals to a%c%b

*** unconcened
模运算及其性质

　　本文以c++语言为载体，对基本的模运算应用进行了分析和程序设计，以理论和实际相结合的方法向大家介绍模运算的基本应用。。
基本理论
　　基本概念：
　　给定一个正整数p，任意一个整数n，一定存在等式 n = kp + r ；
　　其中k、r是整数，且 0 ≤ r < p，称呼k为n除以p的商，r为n除以p的余数。
　　对于正整数p和整数a,b，定义如下运算：
　　取模运算：a % p（或a mod p），表示a除以p的余数。
　　模p加法：(a + b) % p ，其结果是a+b算术和除以p的余数，也就是说，(a+b) = kp +r，则(a + b) % p = r。
　　模p减法：(a-b) % p ，其结果是a-b算术差除以p的余数。
　　模p乘法：(a * b) % p，其结果是 a * b算术乘法除以p的余数。
　　说明：
　　1. 同余式：正整数a，b对p取模，它们的余数相同，记做 a ≡ b % p或者a ≡ b (mod p)。
　　2. n % p得到结果的正负由被除数n决定,与p无关。例如：7%4 = 3， -7%4 = -3， 7%-4 = 3， -7%-4 = -3。
基本性质
　　（1）若p|(a-b)，则a≡b (% p)。例如 11 ≡ 4 (% 7)， 18 ≡ 4(% 7)
　　（2）(a % p)=(b % p)意味a≡b (% p)
　　（3）对称性：a≡b (% p)等价于b≡a (% p)
　　（4）传递性：若a≡b (% p)且b≡c (% p) ，则a≡c (% p)
运算规则
　　模运算与基本四则运算有些相似，但是除法例外。其规则如下：
　　(a + b) % p = (a % p + b % p) % p （1）
　　(a - b) % p = (a % p - b % p) % p （2）
　　(a * b) % p = (a % p * b % p) % p （3）
　　(a^b) % p = ((a % p)^b) % p （4）
　　结合率： ((a+b) % p + c) % p = (a + (b+c) % p) % p （5）
　　((a*b) % p * c)% p = (a * (b*c) % p) % p （6）
　　交换率： (a + b) % p = (b+a) % p （7）
　　(a * b) % p = (b * a) % p （8）
　　分配率： ((a +b)% p * c) % p = ((a * c) % p + (b * c) % p) % p （9）
　　重要定理：若a≡b (% p)，则对于任意的c，都有(a + c) ≡ (b + c) (%p)；（10）
　　若a≡b (% p)，则对于任意的c，都有(a * c) ≡ (b * c) (%p)；（11）
　　若a≡b (% p)，c≡d (% p)，则 (a + c) ≡ (b + d) (%p)，(a - c) ≡ (b - d) (%p)，
　　(a * c) ≡ (b * d) (%p)，(a / c) ≡ (b / d) (%p)； （12）
　　若a≡b (% p)，则对于任意的c，都有ac≡ bc (%p)； （13）

** Modular Exponentiation

#+begin_src cpp
typedef long long ll;
int fastpow(ll a, int b, int c)
{
    ll r = 1 % c;
    while(b)
    {
        if (b & 1)
            r = r * a % c;
        b >>= 1;
        a = a * a % c;
    }
    return (int)r;
}
#+end_src

http://stackoverflow.com/questions/9818129/fastest-algorithm-to-compute-a2nm

** Modular Multiplicative Inverse
** Congruence

- [[http://zh.wikipedia.org/wiki/%E5%90%8C%E4%BD%99#.E6.80.A7.E8.B4.A8][性质]]
  - \(\large a \equiv b \pmod{m} \Rightarrow m | (a-b)\)

  - 传递性
    \[
    \left. \begin{matrix}
    a \equiv b \pmod{m} \\
    b \equiv c \pmod{m}
    \end{matrix} \right\} \Rightarrow a \equiv c \pmod{m}
    \]

  - 加减
    \[
    \left. \begin{matrix}
    a \equiv b \pmod{m} \\
    c \equiv d\pmod{m}
    \end{matrix} \right\} \Rightarrow \left\{ \begin{matrix} a \pm c \equiv b \pm d \pmod{m} \\ ac \equiv bd \pmod{m} \end{matrix} \right.
    \]

  - 变小
    \[a \equiv b \pmod{cn} \Rightarrow a \equiv b \pmod n\]
    \[
    \left. \begin{matrix}
    a \equiv b \pmod{m} \\
    n|m
    \end{matrix} \right\} \Rightarrow a \equiv b \pmod n
    \]

  - 线性同余解的性质
    \[
    \left. \begin{matrix}
    a \equiv b \pmod{m_1} \\
    a \equiv b \pmod{m_2} \\
    \vdots \\
    a \equiv b \pmod{m_n} \\
    (n \ge 2)
    \end{matrix} \right\} \Rightarrow a \equiv b \pmod{lcm(m_1,m_2,\cdots,m_n)}
    \]

** Linear Congruence Theorem

see: http://zh.wikipedia.org/wiki/线性同余方程

形如 \(ax \equiv b \pmod{n}\) 的方程当且仅当 \(\gcd(a,n)|b\) 时有解，解为
\[
\left\{ x_0 + k\frac{n}{\gcd(a,n)} \mid k \in \mathbb{Z} \right\}.
\]
在 \(\mod{n}\) 的完全剩余系 \({0,1,\cdots,n-1}\) 中，恰有 \(d\) 个解。

- 求解\\
  若 \(\gcd(a,n)|b\) ，
  由裴蜀定理，存在整数对 \((r,s)\) 使得 \(ar + sn = \gcd(a,n)\)，因此 \(\large x = r\frac{b}{\gcd(a,n)}\) 是方程的一个解。
  其他的解都关于 \(\large\frac{n}{\gcd(a,n)}\) 与 \(x\) 同余。

** Chinese Remainder Theorem

- 定义
  \(n_1,n_2,\cdots,n_k\) 两两互质，对于序列\(a_1,a_2,\cdots,a_k\)，满足以下同余方程组，求解 \(x\) 。
  \[
  \begin{align}
  x &\equiv a_1 \pmod{n_1} \\
  x &\equiv a_2 \pmod{n_2} \\
  &{}\  \  \vdots \\
  x &\equiv a_k \pmod{n_k}
  \end{align}
  \]

see: http://www.stubc.com/thread-2918-1-7.html
#+begin_src cpp
typedef long long ll;

ll ex_gcd(ll a, ll b, ll& x, ll& y)
{
   ll d;
   if (b == 0) {
       x = 1; y = 0;
       return a;
   }
   d  = ex_gcd(b, a%b, y, x);
   y -= a/b * x;
   return d;
}

ll Chinese_Remainder(ll* a, ll* n, int k) {
    ll N = 1, r = 0;
    for (int i = 0; i < k; ++ i)
        N *= n[i];
    for (int i = 0; i < k; ++ i)
    {
        ll m = N / n[i], x, y;
        ex_gcd(m, n[i], x, y);
        x = (x % n[i] + n[i]) % n[i];
        r = (r + a[i]*m*x) % N;
    }
    return r;
}
#+end_src

- [[http://acm.fzu.edu.cn/problem.php?pid=1402][FZU/1402 - 猪的安家]]
  - A: 模板题

对于一般的情况（即 \(n_1,n_2,\cdots,n_k\) 不两两互质），则满足
\[
a_i \equiv a_j \pmod{\gcd(n_i,n_j)} \qquad \text{for all }i\text{ and }j.
\]
时，[[http://en.wikipedia.org/wiki/Chinese_remainder_theorem#Theorem_statement][有解]]。

see: http://en.wikipedia.org/wiki/Chinese_remainder_theorem#Solution_for_non-coprime_moduli\\
see: http://yzmduncan.iteye.com/blog/1323599\\
see: http://scturtle.is-programmer.com/posts/19363
#+begin_src cpp
typedef long long ll;
typedef pair<ll,ll> mod_p;

ll ex_gcd(ll a, ll b, ll& x, ll& y)
{
   ll d;
   if (b == 0) {
       x = 1; y = 0;
       return a;
   }
   d  = ex_gcd(b, a%b, y, x);
   y -= a/b * x;
   return d;
}

mod_p Chinese_Remainer_Non_Coprime(vector<mod_p> C)
{
    int k = C.size();
    if (k <= 0)
        return make_pair(-1, -1);
    for (int i = k - 2; i >= 0; -- i)
    {
        ll a1 = C[i].first,   n1 = C[i].second;
        ll a2 = C[i+1].first, n2 = C[i+1].second;

        ll c = a2 - a1, p1, p2;
        ll d = ex_gcd(n1, n2, p1, p2);

        if (c % d != 0)
            return make_pair(-1, -1);

        ll t = n2 / d;
        p1 = (c / d * p1 % t + t) % t;
        ll a0 = a1 + n1 * p1;
        ll n0 = n1/d * n2;
        a0 = (a0 % n0 + n0) % n0;

        C[i] = make_pair(a0, n0);
    }
    return C[0];
}
#+end_src

- [[http://poj.org/problem?id%3D2891][POJ/2891 - Strange Way to Express Integers]]
  - A: 模板题
- [[http://acm.hdu.edu.cn/showproblem.php?pid=1573][HDU/1573 - X问题]]
  - Q: 求非互质同余方程组解\(1 \leq x \leq n\)的个数
  - A: 注意0不是解

** Fermat's little theorem

- 若\(p\)为质数，\(\large a^{p} \equiv a \pmod{p}\)
- 若\(a\)不是\(p\)的倍数，\(\large a^{p-1} \equiv 1 \pmod{p}\)

** Euler's theorem

- 若\(a\),\(n\)互质，\(\large a^{\varphi(n)} \equiv 1 \pmod{n}\)
- 求\(\varphi(n)\)
#+begin_src cpp
int eular(int n)
{
    int r = n;
    for(int i = 2; i * i <= n; ++ i)
        if(n % i == 0) {
            r -= r/i;
            while(n % i == 0)
                n /= i;
        }
    if(n != 1)
        r -= r/n;
    return r;
}
#+end_src
- 预处理版本
#+begin_src cpp
const int MAX_N = 100000 + 100;

int phi[MAX_N];

void euler()
{
    for(int i = 1; i < MAX_N; ++ i) phi[i]=i;
    for(int i = 2; i < MAX_N; i+=2) phi[i]/=2;
    for(int i = 3; i < MAX_N; i+=2)
        if(phi[i] == i)
            for(int j = i ; j < MAX_N; j+=i)
                phi[j] = phi[j]/i * (i-1);
}
#+end_src

** 指数循环节

- [[http://hi.baidu.com/aekdycoin/item/e493adc9a7c0870bad092fd9][AC大牛blog]]
\(x \geq \varphi(n)\)时，
\[
\Large A^x \equiv A^{x \mod \varphi(C) + \varphi(C)} \pmod{C}
\]

* Factorial

** 素因子 p 在 n! 中的个数

#+begin_src cpp
//how many p in n!
int prime_factorial(int p, int n)
{
    int cnt = 0, r = n/p;
    while (r) {
        cnt+=r; r/=p;
    }
    return cnt;
}
#+end_src

* Digital Roots

see: http://en.wikipedia.org/wiki/Digital_root
+ [[http://poj.org/problem?id=1519][POJ/1519 - Digital Roots]] or [[http://acm.hdu.edu.cn/showproblem.php?pid=1013][HDU/1013 - Digital Roots]]
  - A: \(dr(n) = 1 + [n-1\pmod 9]\)

* 应用/综合

+ [[http://acm.hdu.edu.cn/showproblem.php?pid%3D4335][HDU/4335 - What is N?]]
  - Q: 满足\(n^{n!} \equiv b \pmod{P} : (0 \leq n \leq M)\) 的 n 有几个。
    其中 \(0 \leq p \leq 10^5, 1 \leq M \leq 2^{64} - 1\)\\
  - A: 利用指数的循环节，小范围暴力\(0 \leq n \leq P\)即可。

+ [[http://acm.hdu.edu.cn/showproblem.php?pid=4350][HDU/4350 - Card]]
  - A: 可从相对位置不变（环）推得，最小循环长度为\(\frac{R}{\gcd(R,R-L+1)}\)。
    
* Others

#+BEGIN_EXAMPLE
1. 1
2. 12
3. 123
   ...
n. 123456789101112...
...
每一组数字都比上一组长 (int)log10((double)i) + 1
#+END_EXAMPLE

** bit

- 位操作实现技巧
  1) 如果要获得第i位的数据，判断((data&(0X<<i))==0),若真，为0，假，为1；
  2) 如果要设置第i位为1，data=(data|(0X1<<i)); 
  3) 如果要设置第i位为0，data=(data&(~(0X1<<i))); 
  4) 如果要将第i位取反，data=(data^(0X1<<i); 
  5) 如果要取出一个数的最后一个1(lowbit)：(data&(-data)) 

** number to rome

zoj3501

* Footnotes

[fn:1] number of primes -- http://en.wikipedia.org/wiki/Prime-counting_function#Table_of_.CF.80.28x.29.2C_x_.2F_ln_x.2C_and_li.28x.29

